version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic-desktop
    steps:
      - checkout
      - run:
          name: Install and Update Packages
          command: |
            echo 'Asia/Jakarta' > /etc/timezone
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            apt update
            apt upgrade -yqq
            apt install -yqq sudo curl wget netcat whois figlet apt-utils software-properties-common
            sudo add-apt-repository ppa:certbot/certbot -y
            sudo apt-get update
            sudo apt-get dist-upgrade -yqq
            sudo apt-get install -y python-certbot-apache
      - run:
          name: Print the Current Time
          command: date
