version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install and Update Packages
          command: apt update && apt upgrade -yqq && apt install -yqq sudo curl wget netcat whois figlet
      - run:
          name: Print the Current Time
          command: date
